package main

import (
	"flag"
	"fmt"
	"path"
	"sort"
	"strings"
	"unicode"
	"unicode/utf8"

	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	var flags flag.FlagSet
	var domain string
	// 可选参数：限定只处理某个业务域目录（例如 welcome）。
	flags.StringVar(&domain, "domain", "", "仅生成某个 domain 目录下的 proto")

	opts := protogen.Options{
		ParamFunc: flags.Set,
	}

	opts.Run(func(plugin *protogen.Plugin) error {
		// 未指定 domain：按输入的所有 proto 正常逐 service 生成。
		if domain == "" {
			for _, file := range plugin.Files {
				if len(file.Services) == 0 {
					continue
				}
				for _, service := range file.Services {
					generateServiceFile(plugin, file, service)
				}
			}
			return nil
		}

		// 指定 domain：筛选后聚合成一个 domain 文件输出。
		domainFiles := collectDomainFiles(plugin.Files, domain)
		if len(domainFiles) == 0 {
			return nil
		}
		generateDomainFile(plugin, domain, domainFiles)
		return nil
	})
}

func collectDomainFiles(files []*protogen.File, domain string) []*protogen.File {
	matched := make([]*protogen.File, 0)
	for _, file := range files {
		if len(file.Services) == 0 {
			continue
		}
		if matchDomain(file.Desc.Path(), domain) {
			matched = append(matched, file)
		}
	}
	return matched
}

func matchDomain(protoPath, domain string) bool {
	d := strings.Trim(domain, "/")
	if d == "" {
		return true
	}
	if protoPath == d+".proto" {
		return true
	}
	return strings.HasPrefix(protoPath, d+"/")
}

func generateDomainFile(plugin *protogen.Plugin, domain string, files []*protogen.File) {
	d := strings.Trim(domain, "/")
	if d == "" {
		return
	}
	// domain 模式固定生成单文件：application/<domain>.go
	fileName := path.Join("application", d+".go")
	baseImportPath := protogen.GoImportPath(path.Join(string(files[0].GoImportPath), "application"))
	g := plugin.NewGeneratedFile(fileName, baseImportPath)

	g.P("// Code generated by protoc-gen-go-skeleton. DO NOT EDIT.")
	g.P("// source domain: ", d)
	g.P()
	g.P("package application")
	g.P()
	g.P("import (")
	g.P(`"context"`)
	g.P(`"google.golang.org/grpc/codes"`)
	g.P(`"google.golang.org/grpc/status"`)

	aliasMap := map[string]string{}
	aliasList := make([]string, 0)
	for _, file := range files {
		importPath := string(file.GoImportPath)
		if _, ok := aliasMap[importPath]; ok {
			continue
		}
		// 多个 pb 包可能同名，这里做别名去重，避免 import 冲突。
		alias := uniqueAlias(string(file.GoPackageName)+"Pb", aliasMap)
		aliasMap[importPath] = alias
		aliasList = append(aliasList, importPath)
	}
	sort.Strings(aliasList)
	for _, importPath := range aliasList {
		g.P(aliasMap[importPath], ` "`, importPath, `"`)
	}
	g.P(")")
	g.P()

	for _, file := range files {
		pbAlias := aliasMap[string(file.GoImportPath)]
		for _, service := range file.Services {
			appName := applicationName(service.GoName)
			g.P("type ", appName, " struct {")
			g.P(pbAlias, ".Unimplemented", service.GoName, "Server")
			g.P("}")
			g.P()

			g.P("func New", appName, "() *", appName, " {")
			g.P("return &", appName, "{}")
			g.P("}")
			g.P()

			for _, method := range service.Methods {
				if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
					g.P("// ", method.GoName, " 为流式 RPC，保留默认未实现行为。")
					continue
				}
				g.P(unaryMethodImpl(appName, pbAlias, method))
				g.P()
			}
		}
	}
}

func uniqueAlias(alias string, aliasMap map[string]string) string {
	exists := map[string]struct{}{}
	for _, v := range aliasMap {
		exists[v] = struct{}{}
	}
	if _, ok := exists[alias]; !ok {
		return alias
	}
	i := 2
	for {
		// 采用 pbAlias2 / pbAlias3 ... 形式递增，直到不冲突。
		candidate := fmt.Sprintf("%s%d", alias, i)
		if _, ok := exists[candidate]; !ok {
			return candidate
		}
		i++
	}
}

func generateServiceFile(plugin *protogen.Plugin, file *protogen.File, service *protogen.Service) {
	appName := applicationName(service.GoName)
	// 默认模式下按 service 拆分文件，方便独立维护。
	fileName := serviceFileName(file.GeneratedFilenamePrefix, service.GoName)
	appImportPath := protogen.GoImportPath(path.Join(string(file.GoImportPath), "application"))
	g := plugin.NewGeneratedFile(fileName, appImportPath)
	pbAlias := string(file.GoPackageName) + "Pb"

	g.P("// Code generated by protoc-gen-go-skeleton. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package application")
	g.P()
	g.P("import (")
	g.P(`"context"`)
	g.P(pbAlias, ` "`, file.GoImportPath, `"`)
	g.P(`"google.golang.org/grpc/codes"`)
	g.P(`"google.golang.org/grpc/status"`)
	g.P(")")
	g.P()

	g.P("type ", appName, " struct {")
	g.P(pbAlias, ".Unimplemented", service.GoName, "Server")
	g.P("}")
	g.P()

	g.P("func New", appName, "() *", appName, " {")
	g.P("return &", appName, "{}")
	g.P("}")
	g.P()

	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
			g.P("// ", method.GoName, " 为流式 RPC，保留默认未实现行为。")
			continue
		}
		g.P(unaryMethodImpl(appName, pbAlias, method))
		g.P()
	}
}

func applicationName(serviceGoName string) string {
	base := trimServiceSuffix(serviceGoName)
	return base + "Application"
}

func serviceFileName(generatedPrefix, serviceGoName string) string {
	dir := path.Dir(generatedPrefix)
	base := toLowerFirst(trimServiceSuffix(serviceGoName))
	if dir == "." || dir == "/" {
		return path.Join("application", base+".go")
	}
	return path.Join(dir, "application", base+".go")
}

func trimServiceSuffix(serviceGoName string) string {
	// WelcomeService -> Welcome，避免生成 WelcomeServiceApplication 这种重复后缀。
	if strings.HasSuffix(serviceGoName, "Service") {
		return strings.TrimSuffix(serviceGoName, "Service")
	}
	return serviceGoName
}

func toLowerFirst(s string) string {
	if s == "" {
		return s
	}
	r, n := utf8.DecodeRuneInString(s)
	return string(unicode.ToLower(r)) + s[n:]
}

func unaryMethodImpl(appName, pbAlias string, method *protogen.Method) string {
	methodName := method.GoName
	inType := pbAlias + "." + method.Input.GoIdent.GoName
	outType := pbAlias + "." + method.Output.GoIdent.GoName
	// 先生成可编译的空实现，后续由业务方补全具体逻辑。
	return fmt.Sprintf("func (app *%s) %s(ctx context.Context, req *%s) (*%s, error) {\n_ = ctx\n_ = req\nreturn nil, status.Error(codes.Unimplemented, \"%s 未实现\")\n}", appName, methodName, inType, outType, methodName)
}
